import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { Providers } from "./store/Provider"

export const metadata = {
  title: "Link de Pagamento - PagBank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers >
      <html lang="pt-br">
        <body>
          <Header />
          <div className="container">
            <Navbar className="navbar" />
            <div className="content">{children}</div>
          </div>
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
